name: CI-CD

on:
  push:
    branches:
      - "feat/**"
      - "*fix/**"
      - "test/**"
      - "refactor/**"
      - "release/[0-9].[0-9].[0-9]"
  pull_request:
    types:
      - closed
    branches:
        - main
        - develop
        - master
jobs:
  pipeline:
    name: 'Pipeline CI-CD'
    uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@main