name: CI-CD ${{ github.ref_name == 'main' && 'production' || 'staging' }}
on:
  push:
    branches:
      - "feat/**"
      - "*fix/**"
      - "test/**"
      - "refactor/**"
      - "release/[0-9].[0-9].[0-9]"
  pull_request:
    types:
      - closed
    branches:
        - main
        - develop
        - master
  workflow_dispatch:

jobs:
  pipeline:
    name: CI-CD ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@develop
    with:
      REGISTY_NAME_FAKE: |
        ${{ github.ref_name == 'main' && vars.REGISTY_NAME_FAKE_PRD || vars.REGISTY_NAME_FAKE_STG }}
      NAME_PROJECT_FAKE: |
        ${{ github.ref_name == 'main' && vars.NAME_PROJECT_FAKE_PRD || vars.NAME_PROJECT_FAKE_STG }}
      LOCATION_DOCKERFILE_DOCKER_COMPOSE_FAKE: |
        ${{ github.ref_name == 'main' && vars.LOCATION_DOCKERFILE_DOCKER_COMPOSE_FAKE_PRD ||
        vars.LOCATION_DOCKERFILE_DOCKER_COMPOSE_FAKE_STG }}
      PROJECT_FAKE: ${{ github.ref_name == 'main' && vars.PROJECT_FAKE_PRD || vars.PROJECT_FAKE_STG }}
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    secrets:
      AZURE_CLIENT_ID_FAKE: ${{ secrets.AZURE_CLIENT_ID_FAKE }}
      AZURE_CLIENT_SECRET_FAKE: ${{ secrets.AZURE_CLIENT_SECRET_FAKE }}
      CREDENTIALS_FAKE: ${{ secrets.CREDENTIALS_FAKE }}
      CORP_REGISTRY_USERNAME_FAKE: ${{ secrets.CORP_REGISTRY_USERNAME_FAKE }}
      CORP_REGISTRY_PASSWORD_FAKE: ${{ secrets.CORP_REGISTRY_PASSWORD_FAKE }}
