name: Validade CI

on:
  push:
    branches:
      -  (feat/**|fix/**|test/**|refactor/**|release/**)
  pull_request:
    branches:
        - (main|develop|master)
jobs:
  pipeline-develop:
    name: 'pipeline-develop'
    uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@main
    with:
      config-path: "test/ci"
    secrets:
      personal_access_token: "validate"