name: CI-CD

on:
  push:
    branches:
      - "feat/**"
      - "*fix/**"
      - "test/**"
      - "refactor/**"
      - "release/[0-9].[0-9].[0-9]"
  pull_request:
    types:
      - closed
    branches:
        - main
        - develop
        - master
jobs:
  pipeline:
    name: 'Pipeline CI-CD'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@develop
        with:
          REGISTY_NAME_FAKE: ${{ vars.REGISTY_NAME_FAKE }}
          NAME_PROJECT_FAKE: ${{ vars.NAME_PROJECT_FAKE }}
          LOCATION_DOCKERFILE_DOCKER_COMPOSE_FAKE: ${{ vars.LOCATION_DOCKERFILE_DOCKER_COMPOSE_FAKE }}
          PROJECT_FAKE: ${{ vars.PROJECT_FAKE }}
          ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    #uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@develop
      
