name: Validade CI

on:
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@main
    with:
      username: Rafael
    secrets:
      personal_access_token: "validate"