name: Validade CI

on:
  push:
    branches:
      - "feat/**"
      - "*fix/**"
      - "test/**"
      - "refactor/**"
      - "release/[0-9].[0-9].[0-9]"
  pull_request:
    types:
      - closed
    branches:
        - main
        - develop
        - master
jobs:
  pipeline-develop:
    name: 'pipeline-develop'
    uses: rafaelrochasantos/poc-centralize-workflow/.github/workflows/poc-github-workflow.yml@198b0a1f118e0ffa5fe45ec9dc44c67a38a8a4b3
    with:
      config-path: "test/ci"
    secrets:
      personal_access_token: "validate"